"""Shared helpers for the reproduction scripts: paths, plot style, table output."""
import json
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
DATA = os.path.join(ROOT, "data")
FIG = os.path.join(ROOT, "paper", "figures")
TAB = os.path.join(ROOT, "paper", "tables")
for _d in (DATA, FIG, TAB):
    os.makedirs(_d, exist_ok=True)

import matplotlib  # noqa: E402
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

plt.rcParams.update({
    "font.family": "serif", "font.size": 9, "axes.labelsize": 9, "legend.fontsize": 7,
    "xtick.labelsize": 8, "ytick.labelsize": 8, "figure.dpi": 150, "axes.linewidth": 0.6,
    "lines.linewidth": 1.1, "savefig.bbox": "tight", "mathtext.fontset": "cm",
})
C = {"blue": "#0072B2", "orange": "#E69F00", "green": "#009E73", "red": "#D55E00",
     "purple": "#CC79A7", "sky": "#56B4E9", "black": "#000000", "grey": "#7f7f7f"}
SINGLE = (3.4, 2.6)
DOUBLE = (7.0, 2.7)


def savefig(fig, name):
    fig.savefig(os.path.join(FIG, name + ".pdf"))
    fig.savefig(os.path.join(FIG, name + ".png"), dpi=200)
    plt.close(fig)


def _conv(o):
    if isinstance(o, (np.floating, np.integer)):
        return o.item()
    if isinstance(o, np.ndarray):
        return o.tolist()
    if isinstance(o, complex):
        return [o.real, o.imag]
    raise TypeError(type(o))


def save_json(obj, name):
    with open(os.path.join(DATA, name + ".json"), "w") as f:
        json.dump(obj, f, indent=1, default=_conv)


def load_json(name):
    with open(os.path.join(DATA, name + ".json")) as f:
        return json.load(f)


def body_variant(text):
    """Tabular without the outer double rules, for REVTeX's ruledtabular."""
    lines = [line for line in text.split("\n") if line.strip()]
    return "\n".join(line for line in lines if line.strip() != "\\hline\\hline") + "\n"


def write_table(name, body):
    # blank lines would end the paragraph inside a tabular
    clean = "\n".join(line for line in body.split("\n") if line.strip()) + "\n"
    header = "% generated by scripts/ -- do not edit by hand\n"
    with open(os.path.join(TAB, name + ".tex"), "w") as f:
        f.write(header + clean)
    with open(os.path.join(TAB, name + "_body.tex"), "w") as f:
        f.write(header + body_variant(clean))


def sci(x, digits=1):
    if x == 0:
        return "$0$"
    if not np.isfinite(x):
        return "--"
    e = int(np.floor(np.log10(abs(x))))
    return f"${x / 10 ** e:.{digits}f}\\times10^{{{e}}}$"
